import { mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import path from "node:path";
import type { Handoff } from "./types";

/**
 * Filesystem store for handoffs (runtime user data — gitignored). DataHub is
 * the sharing surface via save_document write-back; this is the local source
 * of truth so the demo never depends on a document-search round trip.
 */

function storeDir(): string {
  return process.env.HANDOFF_DIR || path.join(process.cwd(), "data", "handoffs");
}

function fileFor(id: string): string {
  // ids are generated by us (see newHandoffId) — sanitize defensively anyway.
  return path.join(storeDir(), `${id.replace(/[^a-zA-Z0-9_-]/g, "")}.json`);
}

export function newHandoffId(title: string): string {
  const slug = title.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "").slice(0, 40) || "handoff";
  return `${slug}-${Date.now().toString(36)}`;
}

export function listHandoffs(): Handoff[] {
  ensureSampleHandoff();
  let files: string[] = [];
  try {
    files = readdirSync(storeDir()).filter((f) => f.endsWith(".json"));
  } catch {
    return [];
  }
  const handoffs: Handoff[] = [];
  for (const file of files) {
    try {
      handoffs.push(JSON.parse(readFileSync(path.join(storeDir(), file), "utf8")) as Handoff);
    } catch {
      /* skip corrupt file */
    }
  }
  return handoffs.sort((a, b) => (b.createdAt || "").localeCompare(a.createdAt || ""));
}

export function getHandoff(id: string): Handoff | null {
  try {
    return JSON.parse(readFileSync(fileFor(id), "utf8")) as Handoff;
  } catch {
    return null;
  }
}

export function saveHandoff(handoff: Handoff): void {
  mkdirSync(storeDir(), { recursive: true });
  writeFileSync(fileFor(handoff.id), JSON.stringify(handoff, null, 2));
}

export function deleteHandoff(id: string): boolean {
  try {
    rmSync(fileFor(id));
    return true;
  } catch {
    return false;
  }
}

/** Render a handoff as markdown for the DataHub save_document write-back. */
export function handoffToMarkdown(handoff: Handoff): string {
  const lines: string[] = [
    `# Handoff: ${handoff.title}`,
    "",
    `Recorded by **${handoff.author}**${handoff.role ? ` (${handoff.role})` : ""} on ${handoff.createdAt.slice(0, 10)}.`,
    "",
    handoff.summary,
    "",
  ];
  handoff.steps.forEach((step, i) => {
    lines.push(`## Step ${i + 1}: ${step.title}`, "");
    lines.push(step.instruction, "");
    lines.push(`**Why:** ${step.why}`, "");
    if (step.urn) lines.push(`**Entity:** \`${step.urn}\``, "");
    if (step.sql) lines.push("```sql", step.sql, "```", "");
    if (step.tips) lines.push(`**Tips:** ${step.tips}`, "");
  });
  lines.push("---", "_Recorded with instaboard. Open the instaboard extension beside DataHub to replay this handoff step by step._");
  return lines.join("\n");
}

/**
 * Ship one sample handoff (matching the seeded Northbeam catalog) so the
 * joiner flow demos even before anyone records — clearly flagged as sample.
 */
export function ensureSampleHandoff(): void {
  const dir = storeDir();
  mkdirSync(dir, { recursive: true });
  const sampleFile = path.join(dir, "sample-monthly-mrr-report.json");
  try {
    readFileSync(sampleFile);
    return; // already there
  } catch {
    /* create below */
  }

  const ui = process.env.DATAHUB_UI_URL || "http://localhost:9002";
  const entity = (urn: string) => `${ui}/dataset/${encodeURIComponent(urn)}`;
  const fctRevenue = "urn:li:dataset:(urn:li:dataPlatform:snowflake,analytics.marts.fct_revenue,PROD)";
  const mrrMonthly = "urn:li:dataset:(urn:li:dataPlatform:snowflake,analytics.marts.mrr_monthly,PROD)";
  const paymentHealth = "urn:li:dataset:(urn:li:dataPlatform:snowflake,analytics.marts.payment_health_daily,PROD)";

  const sample: Handoff = {
    id: "sample-monthly-mrr-report",
    title: "Monthly MRR report for the board deck",
    author: "Priya Patel",
    role: "Payments Data Lead",
    summary:
      "How I produce the MRR numbers for the monthly board deck: sanity-check payment health first, verify the revenue fact loaded, then pull the MRR rollup and hand the numbers to finance.",
    createdAt: "2026-07-01T09:00:00.000Z",
    sample: true,
    steps: [
      {
        title: "Check payment pipeline health",
        instruction:
          "Open payment_health_daily and confirm yesterday's success_rate is above 0.97 for both providers. If it dipped, the revenue numbers may undercount — check with the on-call before reporting anything.",
        why: "A payment outage silently deflates MRR. Finance has been burned by this before — always rule it out first.",
        urn: paymentHealth,
        url: entity(paymentHealth),
        tips: "The saved query 'Payment success rate by provider' on this dataset is the fastest check.",
      },
      {
        title: "Verify fct_revenue loaded cleanly",
        instruction:
          "Open fct_revenue and check the dataset's last updated time and row-count trend. Use net_amount_usd for anything you report — gross_amount_usd includes refunded charges.",
        why: "fct_revenue is the canonical revenue source; every downstream number is wrong if this load was partial.",
        urn: fctRevenue,
        url: entity(fctRevenue),
        sql: "SELECT MAX(revenue_date) AS latest, COUNT(*) AS rows_loaded\nFROM analytics.marts.fct_revenue\nWHERE revenue_date >= DATEADD(day, -35, CURRENT_DATE);",
        tips: "If latest is more than a day behind, ping Mike Rodriguez — the dbt mart job may have failed.",
      },
      {
        title: "Pull the MRR rollup",
        instruction:
          "Open mrr_monthly and run the saved query 'Monthly MRR trend by plan' for the last 12 months. Copy mrr_usd and net_new_mrr_usd into the board template.",
        why: "This table implements the official MRR definition (glossary term MRR) — never recompute it by hand from payments.",
        urn: mrrMonthly,
        url: entity(mrrMonthly),
        sql: "SELECT month, plan, mrr_usd, net_new_mrr_usd\nFROM analytics.marts.mrr_monthly\nWHERE month >= DATEADD(month, -12, CURRENT_DATE)\nORDER BY month, plan;",
        tips: "Board deck wants plan-level rows plus a total — the total is the SUM over plans, not a separate table.",
      },
    ],
    recorded: [
      { url: entity(paymentHealth), urn: paymentHealth, title: "payment_health_daily", note: "Always check this first after an incident-heavy month." },
      { url: entity(fctRevenue), urn: fctRevenue, title: "fct_revenue", note: "net_amount_usd, never gross." },
      { url: entity(mrrMonthly), urn: mrrMonthly, title: "mrr_monthly", note: "Saved query has the exact board cut." },
    ],
    datahub: { saved: false, detail: "Sample handoff — regenerate to write back." },
  };

  writeFileSync(sampleFile, JSON.stringify(sample, null, 2));
}
