"use client";

import type { LearningPath } from "./types";

const PATH_KEY = "instaboard.path";
const PROGRESS_KEY = "instaboard.progress";

export function loadPath(): LearningPath | null {
  if (typeof window === "undefined") return null;
  try {
    const raw = localStorage.getItem(PATH_KEY);
    return raw ? (JSON.parse(raw) as LearningPath) : null;
  } catch {
    return null;
  }
}

export function savePath(path: LearningPath): void {
  localStorage.setItem(PATH_KEY, JSON.stringify(path));
  // A new path resets progress.
  localStorage.removeItem(PROGRESS_KEY);
}

export function loadProgress(): Record<string, boolean> {
  if (typeof window === "undefined") return {};
  try {
    const raw = localStorage.getItem(PROGRESS_KEY);
    return raw ? (JSON.parse(raw) as Record<string, boolean>) : {};
  } catch {
    return {};
  }
}

export function saveProgress(progress: Record<string, boolean>): void {
  localStorage.setItem(PROGRESS_KEY, JSON.stringify(progress));
}

export function itemKey(day: number, index: number): string {
  return `${day}:${index}`;
}

/** Render a learning path as markdown — used for save_document write-back. */
export function pathToMarkdown(path: LearningPath): string {
  const lines: string[] = [
    `# Week 1 Onboarding — ${path.role} (${path.domain})`,
    "",
    path.summary,
    "",
  ];
  for (const day of path.days) {
    lines.push(`## Day ${day.day}: ${day.title}`, "");
    for (const item of day.items) {
      lines.push(`- **${item.title}** — ${item.detail}${item.urn ? ` (\`${item.urn}\`)` : ""}`);
    }
    lines.push("");
  }
  lines.push("---", "_Generated by instaboard from the live DataHub catalog._");
  return lines.join("\n");
}
